// Add more facts and capitals as needed
export default {
  Africa: {
    cities: [
      "Abuja",
      "Accra",
      "Addis Ababa",
      "Algiers",
      "Bamako",
      "Bangui",
      "Banjul",
      "Bissau",
      "Brazzaville",
      "Bujumbura",
      "Cairo",
      "Conakry",
      "Dakar",
      "Djibouti",
      "Dodoma",
      "Freetown",
      "Gaborone",
      "Harare",
      "Kampala",
      "Khartoum",
      "Kigali",
      "Kinshasa",
      "Libreville",
      "Lilongwe",
      "Lome",
      "Luanda",
      "Lusaka",
      "Malabo",
      "Maputo",
      "Maseru",
      "Mbabane",
      "Mogadishu",
      "Monrovia",
      "Nairobi",
      "N'Djamena",
      "Nouakchott",
      "Ouagadougou",
      "Port Louis",
      "Praia",
      "Pretoria",
      "Rabat",
      "Sao Tome",
      "Tripoli",
      "Tunis",
      "Yaounde",
    ],
    interestFacts: [
      "Cairo, Egypt: Cairo is home to the Great Pyramid of Giza, one of the Seven Wonders of the Ancient World.",
      "Cape Town, South Africa: Table Mountain in Cape Town offers breathtaking views and is one of the oldest mountains in the world.",
      "Nairobi, Kenya: Nairobi is known as the 'Green City in the Sun' due to its many parks and green spaces.",
      "Marrakech, Morocco: Marrakech is famous for its vibrant souks (markets), historic medina, and beautiful palaces.",
      "Lagos, Nigeria: Lagos is the most populous city in Nigeria and is a major financial and cultural hub in Africa.",
      "Addis Ababa, Ethiopia: Addis Ababa, the capital of Ethiopia, is home to the African Union headquarters and is the highest capital city in Africa, located at an elevation of 2,355 meters (7,726 feet).",
      "Casablanca, Morocco: Casablanca is Morocco's largest city and a key economic center known for its modern architecture.",
      "Dar es Salaam, Tanzania: Dar es Salaam, located on the Indian Ocean, is a major port city and the largest city in Tanzania.",
      "Dakar, Senegal: Dakar is known for its lively music scene and is considered a cultural hub in West Africa.",
      "Johannesburg, South Africa: Johannesburg is the largest city in South Africa and is often called the 'City of Gold' due to its history of gold mining.",
      "Abuja, Nigeria: Became the capital in 1991, designed to replace Lagos as the capital.",
      "Accra, Ghana: Known for its vibrant markets, colonial-era architecture, and rich history.",
      "Addis Ababa, Ethiopia: The highest capital city in Africa, located at an elevation of 2,355 meters (7,726 feet).",
    ],
  },
  Asia: {
    cities: [
      "Amman",
      "Ashgabat",
      "Astana",
      "Baghdad",
      "Baku",
      "Beijing",
      "Beirut",
      "Bishkek",
      "Colombo",
      "Dhaka",
      "Dili",
      "Dushanbe",
      "Hanoi",
      "Islamabad",
      "Jakarta",
      "Kabul",
      "Kathmandu",
      "Kuala Lumpur",
      "Kuwait City",
      "Male",
      "Manila",
      "Muscat",
      "Naypyidaw",
      "New Delhi",
      "Phnom Penh",
      "Qatar",
      "Riyadh",
      "Seoul",
      "Singapore",
      "Taipei",
      "Tashkent",
      "Tbilisi",
      "Tehran",
      "Thimphu",
      "Tokyo",
      "Yerevan",
    ],
    interestFacts: [
      "Cairo, Egypt: Cairo is home to the Great Pyramid of Giza, one of the Seven Wonders of the Ancient World.",
      "Cape Town, South Africa: Table Mountain in Cape Town offers breathtaking views and is one of the oldest mountains in the world.",
      "Nairobi, Kenya: Nairobi is known as the 'Green City in the Sun' due to its many parks and green spaces.",
      "Marrakech, Morocco: Marrakech is famous for its vibrant souks (markets), historic medina, and beautiful palaces.",
      "Lagos, Nigeria: Lagos is the most populous city in Nigeria and is a major financial and cultural hub in Africa.",
      "Addis Ababa, Ethiopia: Addis Ababa, the capital of Ethiopia, is home to the African Union headquarters and is the highest capital city in Africa, located at an elevation of 2,355 meters (7,726 feet).",
      "Casablanca, Morocco: Casablanca is Morocco's largest city and a key economic center known for its modern architecture.",
      "Dar es Salaam, Tanzania: Dar es Salaam, located on the Indian Ocean, is a major port city and the largest city in Tanzania.",
      "Dakar, Senegal: Dakar is known for its lively music scene and is considered a cultural hub in West Africa.",
      "Johannesburg, South Africa: Johannesburg is the largest city in South Africa and is often called the 'City of Gold' due to its history of gold mining.",
      "Abuja, Nigeria: Became the capital in 1991, designed to replace Lagos as the capital.",
      "Accra, Ghana: Known for its vibrant markets, colonial-era architecture, and rich history.",
      "Addis Ababa, Ethiopia: The highest capital city in Africa, located at an elevation of 2,355 meters (7,726 feet).",
    ],
  },
  Europe: {
    cities: [
      "Amsterdam",
      "Ankara",
      "Athens",
      "Belgrade",
      "Berlin",
      "Bern",
      "Bratislava",
      "Brussels",
      "Bucharest",
      "Budapest",
      "Chisinau",
      "Copenhagen",
      "Dublin",
      "Edinburgh",
      "Helsinki",
      "Kiev",
      "Lisbon",
      "Ljubljana",
      "London",
      "Luxembourg City",
      "Madrid",
      "Minsk",
      "Monaco",
      "Moscow",
      "Oslo",
      "Paris",
      "Podgorica",
      "Prague",
      "Riga",
      "Rome",
      "Sarajevo",
      "Skopje",
      "Sofia",
      "Stockholm",
      "Tallinn",
      "The Hague",
      "Tirana",
      "Vaduz",
      "Valletta",
      "Vatican City",
      "Vienna",
      "Vilnius",
      "Warsaw",
      "Zagreb",
      "Zurich",
    ],
    interestFacts: [
      "Amsterdam, Netherlands: Famous for its picturesque canals, historic architecture, and vibrant culture.",
      "Ankara, Turkey: Capital known for its Hittite, Phrygian, Hellenistic, Roman, Byzantine, and Ottoman archaeological sites.",
      "Berlin, Germany: The capital and largest city, known for its cultural institutions, museums, and vibrant nightlife.",
      "Madrid, Spain: Madrid is the highest capital city in Europe, located at an elevation of approximately 2,180 feet (664 meters) above sea level.",
      "Lisbon, Portugal: Lisbon is one of the oldest cities in Western Europe, predating other European capitals such as Paris and Rome by centuries.",
      "Vienna, Austria: Vienna is often referred to as the 'City of Music' due to its rich musical heritage, including famous composers like Mozart, Beethoven, and Strauss.",
      "Stockholm, Sweden: Stockholm is known for its unique archipelago, consisting of thousands of islands, making it one of the most beautiful and diverse capitals in the world.",
      "Warsaw, Poland: Warsaw's Old Town is a UNESCO World Heritage Site and was meticulously reconstructed after being heavily damaged during World War II.",
      "Athens, Greece: Athens is widely considered the birthplace of democracy and is home to iconic ancient landmarks like the Acropolis.",
      "Oslo, Norway: Oslo is surrounded by a beautiful fjord and has a strong maritime history. The city's Viking Ship Museum displays well-preserved Viking ships.",
      "Copenhagen, Denmark: Copenhagen is famous for its bike-friendly infrastructure and is often ranked as one of the most bicycle-friendly cities in the world.",
      "Helsinki, Finland: Helsinki has a design district known for its modern architecture and design shops, reflecting Finland's emphasis on innovation and aesthetics.",
      "Prague, Czech Republic: Prague is home to the largest ancient castle in the world, Prague Castle, which has been the seat of kings, emperors, and presidents for over 1,000 years.",
    ],
  },
  "North America": {
    cities: [
      "Belmopan",
      "Bridgetown",
      "Castries",
      "Havana",
      "Kingston",
      "Kingstown",
      "Managua",
      "Mexico City",
      "Nassau",
      "Ottawa",
      "Panama City",
      "Port-au-Prince",
      "Roseau",
      "Saint George's",
      "Saint John's",
      "San Jose",
      "San Salvador",
      "Washington, D.C.",
      "Belmopan",
      "Bridgetown",
      "Castries",
      "Havana",
      "Kingston",
      "Kingstown",
      "Managua",
      "Mexico City",
      "Nassau",
      "Ottawa",
      "Panama City",
      "Port-au-Prince",
      "Roseau",
      "Saint George's",
      "Saint John's",
      "San Jose",
      "San Salvador",
      "Washington, D.C.",
      "Belize City",
      "Toronto",
      "Guatemala City",
      "Havana",
      "Mexico City",
      "Tegucigalpa",
    ],
    interestFacts: [
      "Belmopan, Belize: One of the smallest capital cities in the world.",
      "Bridgetown, Barbados: Has a UNESCO-listed historic area and is the capital of Barbados.",
      "Ottawa, Canada: Ottawa is the capital and fourth-largest city, known for its historic architecture and national institutions.",
      "Washington, D.C., USA: The capital of the United States, known for iconic landmarks such as the White House, Capitol Building, and National Mall.",
      "Mexico City, Mexico: One of the oldest capitals in the Americas, known for its rich history, vibrant culture, and archaeological sites like Teotihuacan.",
      "Guatemala City, Guatemala: The largest city and capital, known for its Mayan archaeological sites and cultural heritage.",
      "Havana, Cuba: The capital and largest city, known for its colorful architecture, vintage cars, and vibrant music scene.",
      "Panama City, Panama: A major financial hub and the capital, known for the Panama Canal and a mix of modern and historic architecture.",
    ],
  },
  Oceania: {
    cities: [
      "Apia",
      "Canberra",
      "Funafuti",
      "Honiara",
      "Majuro",
      "Nuku'alofa",
      "Palikir",
      "Port Moresby",
      "Suva",
      "Wellington",
      "Noumea",
      "Papeete",
      "Hagåtña",
      "Majuro",
      "Yaren",
      "Saipan",
    ],
    interestFacts: [
      "Apia, Samoa: Capital and largest city situated on the central north coast of Upolu.",
      "Canberra, Australia: Selected as the capital in 1908 as a compromise between Sydney and Melbourne.",
      "Wellington, New Zealand: The capital and second-most populous city, known for its film industry and vibrant arts scene.",
      "Nuku'alofa, Tonga: Translates to 'Abode of Love' and serves as the capital and largest city of Tonga.",
      "Honiara, Solomon Islands: Named after the 80-meter high Mount Austin, known for its World War II history and cultural diversity.",
      "Majuro, Marshall Islands: Capital and largest city, located on the Majuro Atoll, known for its coral reefs and traditional dance festivals.",
      "Palikir, Federated States of Micronesia: The fourth smallest capital in the world by population, located on the island of Pohnpei.",
      "Port Moresby, Papua New Guinea: Translates to 'Harbor' and is known for its diverse cultures, wildlife, and natural beauty.",
      "Suva, Fiji: The largest city and capital, known for its colonial architecture, vibrant markets, and cultural events.",
      "Nouméa, New Caledonia: Capital and largest city, known for its French-influenced culture, lagoons, and Kanak traditions.",
      "Papeete, French Polynesia: Serves as the capital of French Polynesia, known for its tropical paradise, black sand beaches, and vibrant nightlife.",
      "Hagåtña, Guam: The capital and largest city, known for its Chamorro culture, historical sites, and beautiful landscapes.",
      "Yaren, Nauru: The de facto capital and largest city, known for its phosphate mining history and Micronesian culture.",
      "Saipan, Northern Mariana Islands: The largest island and capital, known for its World War II history, diverse marine life, and scenic landscapes.",
    ],
  },
  "South America": {
    cities: [
      "Cayenne",
      "Montevideo",
      "Lima",
      "La Paz",
      "São Paulo",
      "Bogota",
      "Brasilia",
      "Buenos Aires",
      "Caracas",
      "Georgetown",
      "Paramaribo",
      "Quito",
      "Santiago",
      "Sucre",
      "Vaduz",
    ],
    interestFacts: [
      "Asuncion, Paraguay: One of the oldest cities in South America.",
      "Bogota, Colombia: Located at an elevation of 2,640 meters (8,660 feet) above sea level.",
      "Brasilia, Brazil: The capital, known for its modernist architecture and urban planning.",
      "Buenos Aires, Argentina: Known as the 'Paris of South America' for its European-style architecture, cultural richness, and tango music.",
      "Caracas, Venezuela: The northernmost capital of South America, situated close to the Caribbean Sea and known for its historic landmarks.",
      "Georgetown, Guyana: The capital and largest city, known for its diverse population, colonial architecture, and botanical gardens.",
      "Paramaribo, Suriname: The largest city and capital, known for its wooden colonial architecture and multicultural heritage.",
      "Quito, Ecuador: The highest official capital city in the world, situated at an elevation of 2,850 meters (9,350 feet) above sea level.",
      "Santiago, Chile: Surrounded by the Andes Mountains, known for its vibrant culture, museums, and historic neighborhoods.",
      "Sucre, Bolivia: The constitutional capital and seat of the Supreme Court, known for its well-preserved colonial architecture.",
      "Vaduz, Liechtenstein: One of the smallest capital cities in the world, known for its medieval castle and as the residence of the Prince of Liechtenstein.",
      "Cayenne, French Guiana: The capital and largest city, known for its blend of French and Creole cultures, tropical rainforests, and diverse wildlife.",
      "Montevideo, Uruguay: The largest city and capital, known for its beaches, cultural events, and historic districts.",
      "Lima, Peru: The capital and largest city, founded by Spanish conquistador Francisco Pizarro, known for its historical sites and culinary scene.",
      "La Paz, Bolivia: The seat of government and executive capital, known for its unique topography and indigenous culture.",
      "São Paulo, Brazil: The largest city in South America, known for its economic importance, cultural events, and diverse population.",
    ],
  },
  "All Capitals": {
    cities: ["Abuja",
      "Accra",
      "Addis Ababa",
      "Algiers",
      "Bamako",
      "Bangui",
      "Banjul",
      "Bissau",
      "Brazzaville",
      "Bujumbura",
      "Cairo",
      "Conakry",
      "Dakar",
      "Djibouti",
      "Dodoma",
      "Freetown",
      "Gaborone",
      "Harare",
      "Kampala",
      "Khartoum",
      "Kigali",
      "Kinshasa",
      "Libreville",
      "Lilongwe",
      "Lome",
      "Luanda",
      "Lusaka",
      "Malabo",
      "Maputo",
      "Maseru",
      "Mbabane",
      "Mogadishu",
      "Monrovia",
      "Nairobi",
      "N'Djamena",
      "Nouakchott",
      "Ouagadougou",
      "Port Louis",
      "Praia",
      "Pretoria",
      "Rabat",
      "Sao Tome",
      "Tripoli",
      "Tunis",
      "Yaounde",
      "Amman",
      "Ashgabat",
      "Astana",
      "Baghdad",
      "Baku",
      "Beijing",
      "Beirut",
      "Bishkek",
      "Colombo",
      "Dhaka",
      "Dili",
      "Dushanbe",
      "Hanoi",
      "Islamabad",
      "Jakarta",
      "Kabul",
      "Kathmandu",
      "Kuala Lumpur",
      "Kuwait City",
      "Male",
      "Manila",
      "Muscat",
      "Naypyidaw",
      "New Delhi",
      "Phnom Penh",
      "Qatar",
      "Riyadh",
      "Seoul",
      "Singapore",
      "Taipei",
      "Tashkent",
      "Tbilisi",
      "Tehran",
      "Thimphu",
      "Tokyo",
      "Yerevan",
      "Amsterdam",
      "Ankara",
      "Athens",
      "Belgrade",
      "Berlin",
      "Bern",
      "Bratislava",
      "Brussels",
      "Bucharest",
      "Budapest",
      "Chisinau",
      "Copenhagen",
      "Dublin",
      "Edinburgh",
      "Helsinki",
      "Kiev",
      "Lisbon",
      "Ljubljana",
      "London",
      "Luxembourg City",
      "Madrid",
      "Minsk",
      "Monaco",
      "Moscow",
      "Oslo",
      "Paris",
      "Podgorica",
      "Prague",
      "Riga",
      "Rome",
      "Sarajevo",
      "Skopje",
      "Sofia",
      "Stockholm",
      "Tallinn",
      "The Hague",
      "Tirana",
      "Vaduz",
      "Valletta",
      "Vatican City",
      "Vienna",
      "Vilnius",
      "Warsaw",
      "Zagreb",
      "Zurich",
      "Belmopan",
      "Bridgetown",
      "Castries",
      "Havana",
      "Kingston",
      "Kingstown",
      "Managua",
      "Mexico City",
      "Nassau",
      "Ottawa",
      "Panama City",
      "Port-au-Prince",
      "Roseau",
      "Saint George's",
      "Saint John's",
      "San Jose",
      "San Salvador",
      "Washington, D.C.",
      "Belmopan",
      "Bridgetown",
      "Castries",
      "Havana",
      "Kingston",
      "Kingstown",
      "Managua",
      "Mexico City",
      "Nassau",
      "Ottawa",
      "Panama City",
      "Port-au-Prince",
      "Roseau",
      "Saint George's",
      "Saint John's",
      "San Jose",
      "San Salvador",
      "Washington, D.C.",
      "Belize City",
      "Toronto",
      "Guatemala City",
      "Havana",
      "Mexico City",
      "Tegucigalpa",
      "Apia",
      "Canberra",
      "Funafuti",
      "Honiara",
      "Majuro",
      "Nuku'alofa",
      "Palikir",
      "Port Moresby",
      "Suva",
      "Wellington",
      "Noumea",
      "Papeete",
      "Hagåtña",
      "Majuro",
      "Yaren",
      "Saipan",
      "Cayenne",
      "Montevideo",
      "Lima",
      "La Paz",
      "São Paulo",
      "Bogota",
      "Brasilia",
      "Buenos Aires",
      "Caracas",
      "Georgetown",
      "Paramaribo",
      "Quito",
      "Santiago",
      "Sucre",
      "Vaduz",
    ],
    interestFacts: [
      "Cairo, Egypt: Cairo is home to the Great Pyramid of Giza, one of the Seven Wonders of the Ancient World.",
      "Cape Town, South Africa: Table Mountain in Cape Town offers breathtaking views and is one of the oldest mountains in the world.",
      "Nairobi, Kenya: Nairobi is known as the 'Green City in the Sun' due to its many parks and green spaces.",
      "Marrakech, Morocco: Marrakech is famous for its vibrant souks (markets), historic medina, and beautiful palaces.",
      "Lagos, Nigeria: Lagos is the most populous city in Nigeria and is a major financial and cultural hub in Africa.",
      "Addis Ababa, Ethiopia: Addis Ababa, the capital of Ethiopia, is home to the African Union headquarters and is the highest capital city in Africa, located at an elevation of 2,355 meters (7,726 feet).",
      "Casablanca, Morocco: Casablanca is Morocco's largest city and a key economic center known for its modern architecture.",
      "Dar es Salaam, Tanzania: Dar es Salaam, located on the Indian Ocean, is a major port city and the largest city in Tanzania.",
      "Dakar, Senegal: Dakar is known for its lively music scene and is considered a cultural hub in West Africa.",
      "Johannesburg, South Africa: Johannesburg is the largest city in South Africa and is often called the 'City of Gold' due to its history of gold mining.",
      "Abuja, Nigeria: Became the capital in 1991, designed to replace Lagos as the capital.",
      "Accra, Ghana: Known for its vibrant markets, colonial-era architecture, and rich history.",
      "Addis Ababa, Ethiopia: The highest capital city in Africa, located at an elevation of 2,355 meters (7,726 feet).",
      "Cairo, Egypt: Cairo is home to the Great Pyramid of Giza, one of the Seven Wonders of the Ancient World.",
      "Cape Town, South Africa: Table Mountain in Cape Town offers breathtaking views and is one of the oldest mountains in the world.",
      "Nairobi, Kenya: Nairobi is known as the 'Green City in the Sun' due to its many parks and green spaces.",
      "Marrakech, Morocco: Marrakech is famous for its vibrant souks (markets), historic medina, and beautiful palaces.",
      "Lagos, Nigeria: Lagos is the most populous city in Nigeria and is a major financial and cultural hub in Africa.",
      "Addis Ababa, Ethiopia: Addis Ababa, the capital of Ethiopia, is home to the African Union headquarters and is the highest capital city in Africa, located at an elevation of 2,355 meters (7,726 feet).",
      "Casablanca, Morocco: Casablanca is Morocco's largest city and a key economic center known for its modern architecture.",
      "Dar es Salaam, Tanzania: Dar es Salaam, located on the Indian Ocean, is a major port city and the largest city in Tanzania.",
      "Dakar, Senegal: Dakar is known for its lively music scene and is considered a cultural hub in West Africa.",
      "Johannesburg, South Africa: Johannesburg is the largest city in South Africa and is often called the 'City of Gold' due to its history of gold mining.",
      "Abuja, Nigeria: Became the capital in 1991, designed to replace Lagos as the capital.",
      "Accra, Ghana: Known for its vibrant markets, colonial-era architecture, and rich history.",
      "Addis Ababa, Ethiopia: The highest capital city in Africa, located at an elevation of 2,355 meters (7,726 feet).",
      "Ankara, Turkey: Capital known for its Hittite, Phrygian, Hellenistic, Roman, Byzantine, and Ottoman archaeological sites.",
      "Berlin, Germany: The capital and largest city, known for its cultural institutions, museums, and vibrant nightlife.",
      "Madrid, Spain: Madrid is the highest capital city in Europe, located at an elevation of approximately 2,180 feet (664 meters) above sea level.",
      "Lisbon, Portugal: Lisbon is one of the oldest cities in Western Europe, predating other European capitals such as Paris and Rome by centuries.",
      "Vienna, Austria: Vienna is often referred to as the 'City of Music' due to its rich musical heritage, including famous composers like Mozart, Beethoven, and Strauss.",
      "Stockholm, Sweden: Stockholm is known for its unique archipelago, consisting of thousands of islands, making it one of the most beautiful and diverse capitals in the world.",
      "Warsaw, Poland: Warsaw's Old Town is a UNESCO World Heritage Site and was meticulously reconstructed after being heavily damaged during World War II.",
      "Athens, Greece: Athens is widely considered the birthplace of democracy and is home to iconic ancient landmarks like the Acropolis.",
      "Oslo, Norway: Oslo is surrounded by a beautiful fjord and has a strong maritime history. The city's Viking Ship Museum displays well-preserved Viking ships.",
      "Copenhagen, Denmark: Copenhagen is famous for its bike-friendly infrastructure and is often ranked as one of the most bicycle-friendly cities in the world.",
      "Helsinki, Finland: Helsinki has a design district known for its modern architecture and design shops, reflecting Finland's emphasis on innovation and aesthetics.",
      "Prague, Czech Republic: Prague is home to the largest ancient castle in the world, Prague Castle, which has been the seat of kings, emperors, and presidents for over 1,000 years.",
      "Belmopan, Belize: One of the smallest capital cities in the world.",
      "Bridgetown, Barbados: Has a UNESCO-listed historic area and is the capital of Barbados.",
      "Ottawa, Canada: Ottawa is the capital and fourth-largest city, known for its historic architecture and national institutions.",
      "Washington, D.C., USA: The capital of the United States, known for iconic landmarks such as the White House, Capitol Building, and National Mall.",
      "Mexico City, Mexico: One of the oldest capitals in the Americas, known for its rich history, vibrant culture, and archaeological sites like Teotihuacan.",
      "Guatemala City, Guatemala: The largest city and capital, known for its Mayan archaeological sites and cultural heritage.",
      "Havana, Cuba: The capital and largest city, known for its colorful architecture, vintage cars, and vibrant music scene.",
      "Panama City, Panama: A major financial hub and the capital, known for the Panama Canal and a mix of modern and historic architecture.",
      "Asuncion, Paraguay: One of the oldest cities in South America.",
      "Bogota, Colombia: Located at an elevation of 2,640 meters (8,660 feet) above sea level.",
      "Brasilia, Brazil: The capital, known for its modernist architecture and urban planning.",
      "Apia, Samoa: Capital and largest city situated on the central north coast of Upolu.",
      "Canberra, Australia: Selected as the capital in 1908 as a compromise between Sydney and Melbourne.",
      "Wellington, New Zealand: The capital and second-most populous city, known for its film industry and vibrant arts scene.",
      "Nuku'alofa, Tonga: Translates to 'Abode of Love' and serves as the capital and largest city of Tonga.",
      "Honiara, Solomon Islands: Named after the 80-meter high Mount Austin, known for its World War II history and cultural diversity.",
      "Majuro, Marshall Islands: Capital and largest city, located on the Majuro Atoll, known for its coral reefs and traditional dance festivals.",
      "Palikir, Federated States of Micronesia: The fourth smallest capital in the world by population, located on the island of Pohnpei.",
      "Port Moresby, Papua New Guinea: Translates to 'Harbor' and is known for its diverse cultures, wildlife, and natural beauty.",
      "Suva, Fiji: The largest city and capital, known for its colonial architecture, vibrant markets, and cultural events.",
      "Nouméa, New Caledonia: Capital and largest city, known for its French-influenced culture, lagoons, and Kanak traditions.",
      "Papeete, French Polynesia: Serves as the capital of French Polynesia, known for its tropical paradise, black sand beaches, and vibrant nightlife.",
      "Hagåtña, Guam: The capital and largest city, known for its Chamorro culture, historical sites, and beautiful landscapes.",
      "Yaren, Nauru: The de facto capital and largest city, known for its phosphate mining history and Micronesian culture.",
      "Saipan, Northern Mariana Islands: The largest island and capital, known for its World War II history, diverse marine life, and scenic landscapes.",
      "Asuncion, Paraguay: One of the oldest cities in South America.",
      "Bogota, Colombia: Located at an elevation of 2,640 meters (8,660 feet) above sea level.",
      "Brasilia, Brazil: The capital, known for its modernist architecture and urban planning.",
      "Buenos Aires, Argentina: Known as the 'Paris of South America' for its European-style architecture, cultural richness, and tango music.",
      "Caracas, Venezuela: The northernmost capital of South America, situated close to the Caribbean Sea and known for its historic landmarks.",
      "Georgetown, Guyana: The capital and largest city, known for its diverse population, colonial architecture, and botanical gardens.",
      "Paramaribo, Suriname: The largest city and capital, known for its wooden colonial architecture and multicultural heritage.",
      "Quito, Ecuador: The highest official capital city in the world, situated at an elevation of 2,850 meters (9,350 feet) above sea level.",
      "Santiago, Chile: Surrounded by the Andes Mountains, known for its vibrant culture, museums, and historic neighborhoods.",
      "Sucre, Bolivia: The constitutional capital and seat of the Supreme Court, known for its well-preserved colonial architecture.",
      "Vaduz, Liechtenstein: One of the smallest capital cities in the world, known for its medieval castle and as the residence of the Prince of Liechtenstein.",
      "Cayenne, French Guiana: The capital and largest city, known for its blend of French and Creole cultures, tropical rainforests, and diverse wildlife.",
      "Montevideo, Uruguay: The largest city and capital, known for its beaches, cultural events, and historic districts.",
      "Lima, Peru: The capital and largest city, founded by Spanish conquistador Francisco Pizarro, known for its historical sites and culinary scene.",
      "La Paz, Bolivia: The seat of government and executive capital, known for its unique topography and indigenous culture.",
      "São Paulo, Brazil: The largest city in South America, known for its economic importance, cultural events, and diverse population.",
    ]
  }
};
